services:
  backend:
    build: .
    ports:
      - "8084:80"
    env_file:
      - ./app/.env
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/.env

volumes:
  postgres_data:
